//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenantBillReport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TenantDatabaseEntities : DbContext
    {
        public TenantDatabaseEntities()
            : base("name=TenantDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BillInvoice> BillInvoices { get; set; }
        public DbSet<BillPayable> BillPayables { get; set; }
        public DbSet<BillPayment> BillPayments { get; set; }
        public DbSet<Building> Buildings { get; set; }
        public DbSet<Tenant> Tenants { get; set; }
        public DbSet<TenantMeterReading> TenantMeterReadings { get; set; }
    }
}
