//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenantBillReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public Tenant()
        {
            this.BillInvoices = new HashSet<BillInvoice>();
            this.BillPayables = new HashSet<BillPayable>();
            this.BillPayments = new HashSet<BillPayment>();
            this.TenantMeterReadings = new HashSet<TenantMeterReading>();
        }
    
        public int TenantId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string FloorNumber { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<BillInvoice> BillInvoices { get; set; }
        public virtual ICollection<BillPayable> BillPayables { get; set; }
        public virtual ICollection<BillPayment> BillPayments { get; set; }
        public virtual Building Building { get; set; }
        public virtual ICollection<TenantMeterReading> TenantMeterReadings { get; set; }
    }
}
